### ISSUE TITLE
After call clear() EventListener not restored anymore

### ISSUE THREAD

**Issue by Akiyamka** [freaksauce/window-resize#1]
When we add first callback - EventListener added too.
```
add: (callback) => {
  if (!callbacks.length) {
    window.addEventListener('resize', resize)
  }
  addCallback(callback)
}
```
When we run clear() after that - EventListener removed, but stored callbacks not cleared.
```
clear: () => {
  window.removeEventListener('resize', resize)
}
```
So if we want `add()` callback again nothing happened, because  `!callbacks.length` return n > 0

**Comment by freaksauce** [comment]
Yeah I think this whole function could be simplified, it is written to be a generic function but then has a specific role... I think I'll refactor

**Comment by freaksauce** [comment]
Please update to v0.0.5
